version: 2.1
executors:

  terraform:
    docker:
      - image: wesleycharlesblake/devops-tools:0.1.18

jobs:
  validate:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Terraform Validate
          command: |
            printf 'credentials "app.terraform.io" { \n  token = "%s" \n}\n' "$ATLAS_TOKEN" > ~/.terraformrc
            terraform init
            terraform validate
          no_output_timeout: 30m

  plan:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Terraform Plan
          command: |
            printf 'credentials "app.terraform.io" { \n  token = "%s" \n}\n' "$ATLAS_TOKEN" > ~/.terraformrc
            terraform init
            terraform plan
          no_output_timeout: 30m

  release:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Release-it
          command: |
            npm install
            npm release-it --ci


workflows:
  version: 2
  build-and-deploy:
    jobs:

      - validate:
          context: CI
      - plan:
          context: CI
          requires:
            - validate
      - release:
          context: CI
          requires:
            - plan
          filters:
            branches:
              only: master
